{
 "title": "workqueue",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "controller",
    "label": "controller",
    "query": {
     "query": "label_values(workqueue_dequeue_total{}, job)"
    }
   },
   {
    "name": "queue",
    "label": "queuename",
    "query": {
     "query": "label_values(workqueue_dequeue_total{job=\"$controller\"}, queuename)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "SLA",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "workqueue_reconcile_duration{job=\"$controller\", queuename=\"$queue\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "reconcile_succ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(workqueue_reconcile_succ_total{job=\"$controller\",queuename=\"$queue\"}[1m]) * 60",
     "legendFormat": "rate"
    }
   ]
  },
  {
   "title": "reconcile_fail",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(workqueue_reconcile_fail_total{job=\"$controller\",queuename=\"$queue\"}[1m]) * 60",
     "legendFormat": "rate"
    }
   ]
  },
  {
   "title": "dequeue",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(workqueue_dequeue_total{job=\"$controller\",queuename=\"$queue\"}[1m])*60",
     "legendFormat": "rate"
    }
   ]
  },
  {
   "title": "requeue_rate_limit",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 7, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(workqueue_requeue_rate_limit_total{job=\"$controller\",queuename=\"$queue\"}[1m]) * 60",
     "legendFormat": "rate"
    }
   ]
  },
  {
   "title": "requeue_after",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(workqueue_requeue_after_total{job=\"$controller\",queuename=\"$queue\"}[1m]) * 60",
     "legendFormat": "rate"
    }
   ]
  },
  {
   "title": "unexpected_obj",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(workqueue_unexpected_obj_total{job=\"$controller\",queuename=\"$queue\"}[1m]) * 60",
     "legendFormat": "rate"
    }
   ]
  }
 ]
}